### PR TITLE
libfreeipmi/ipmi-sensor-read.c: Incorrect sensor reading reported

### PR DESCRIPTION
**Pull request by casual-lemon**
Incorrect sensor reading reported with ipmi-sensor

Fixes: #42

### CODE REVIEW

**Comment by chu11** [comment]
Doh!  Good catch and thanks for the fix.  Does ubuntu/canonical need an upstream release soon?

**Comment by casual-lemon** [comment]
Hi o/

I didn't expect this to get merged so quickly!! Thanks.

Yeah we do ;) 

Cheers

**Comment by chu11** [comment]
You're welcome, thanks for the fix.  I will try and do a release later this week.

**Comment by chu11** [comment]
I lied, I released it tonight :-)

**Pull request merged**
