### PR TITLE
enable building on cygwin

### PR DESCRIPTION
**Pull request by crd477**
Signed-off-by: Chad Dougherty <crd@acm.org>

### CODE REVIEW

**Comment by crd477** [comment]
Without this patch, freeipmi fails to build the included argp library on Cygwin with the following errors:
```
$ make -j4
...
Making all in portability
make[2]: Entering directory '/cygdrive/c/Users/crd/src/freeipmi-1.6.10/common/portability'
/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../config  -D_GNU_SOURCE -D_REENTRANT   -g -O2 -MT libportability_la-freeipmi-argp-fmtstream.lo -MD -MP -MF .deps/libportability_la-freeipmi-argp-fmtstream.Tpo -c -o libportability_la-freeipmi-argp-fmtstream.lo `test -f 'freeipmi-argp-fmtstream.c' || echo './'`freeipmi-argp-fmtstream.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../config -D_GNU_SOURCE -D_REENTRANT -g -O2 -MT libportability_la-freeipmi-argp-fmtstream.lo -MD -MP -MF .deps/libportability_la-freeipmi-argp-fmtstream.Tpo -c freeipmi-argp-fmtstream.c  -DDLL_EXPORT -DPIC -o .libs/libportability_la-freeipmi-argp-fmtstream.o
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:62:32: error: redefinition of 'argp_fmtstream_write'
   62 | #define __argp_fmtstream_write argp_fmtstream_write
      |                                ^~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:395:1: note: in expansion of macro '__argp_fmtstream_write'
  395 | __argp_fmtstream_write (argp_fmtstream_t __fs,
      | ^~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:201:32: note: previous definition of 'argp_fmtstream_write' with type 'size_t(struct argp_fmtstream *, const char *, size_t)' {aka 'long unsigned int(struct argp_fmtstream *, const char *, long unsigned int)'}
  201 | #define __argp_fmtstream_write argp_fmtstream_write
      |                                ^~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:215:1: note: in expansion of macro '__argp_fmtstream_write'
  215 | __argp_fmtstream_write (argp_fmtstream_t __fs,
      | ^~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:60:31: error: redefinition of 'argp_fmtstream_puts'
   60 | #define __argp_fmtstream_puts argp_fmtstream_puts
      |                               ^~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:409:1: note: in expansion of macro '__argp_fmtstream_puts'
  409 | __argp_fmtstream_puts (argp_fmtstream_t __fs, __const char *__str)
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:200:31: note: previous definition of 'argp_fmtstream_puts' with type 'int(struct argp_fmtstream *, const char *)'
  200 | #define __argp_fmtstream_puts argp_fmtstream_puts
      |                               ^~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:229:1: note: in expansion of macro '__argp_fmtstream_puts'
  229 | __argp_fmtstream_puts (argp_fmtstream_t __fs, __const char *__str)
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:58:31: error: redefinition of 'argp_fmtstream_putc'
   58 | #define __argp_fmtstream_putc argp_fmtstream_putc
      |                               ^~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:422:1: note: in expansion of macro '__argp_fmtstream_putc'
  422 | __argp_fmtstream_putc (argp_fmtstream_t __fs, int __ch)
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:199:31: note: previous definition of 'argp_fmtstream_putc' with type 'int(struct argp_fmtstream *, int)'
  199 | #define __argp_fmtstream_putc argp_fmtstream_putc
      |                               ^~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:242:1: note: in expansion of macro '__argp_fmtstream_putc'
  242 | __argp_fmtstream_putc (argp_fmtstream_t __fs, int __ch)
      | ^~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:66:38: error: redefinition of 'argp_fmtstream_set_lmargin'
   66 | #define __argp_fmtstream_set_lmargin argp_fmtstream_set_lmargin
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:432:1: note: in expansion of macro '__argp_fmtstream_set_lmargin'
  432 | __argp_fmtstream_set_lmargin (argp_fmtstream_t __fs, size_t __lmargin)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:202:38: note: previous definition of 'argp_fmtstream_set_lmargin' with type 'size_t(struct argp_fmtstream *, size_t)' {aka 'long unsigned int(struct argp_fmtstream *, long unsigned int)'}
  202 | #define __argp_fmtstream_set_lmargin argp_fmtstream_set_lmargin
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:252:1: note: in expansion of macro '__argp_fmtstream_set_lmargin'
  252 | __argp_fmtstream_set_lmargin (argp_fmtstream_t __fs, size_t __lmargin)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:68:38: error: redefinition of 'argp_fmtstream_set_rmargin'
   68 | #define __argp_fmtstream_set_rmargin argp_fmtstream_set_rmargin
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:444:1: note: in expansion of macro '__argp_fmtstream_set_rmargin'
  444 | __argp_fmtstream_set_rmargin (argp_fmtstream_t __fs, size_t __rmargin)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:203:38: note: previous definition of 'argp_fmtstream_set_rmargin' with type 'size_t(struct argp_fmtstream *, size_t)' {aka 'long unsigned int(struct argp_fmtstream *, long unsigned int)'}
  203 | #define __argp_fmtstream_set_rmargin argp_fmtstream_set_rmargin
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:264:1: note: in expansion of macro '__argp_fmtstream_set_rmargin'
  264 | __argp_fmtstream_set_rmargin (argp_fmtstream_t __fs, size_t __rmargin)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:70:38: error: redefinition of 'argp_fmtstream_set_wmargin'
   70 | #define __argp_fmtstream_set_wmargin argp_fmtstream_set_wmargin
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:456:1: note: in expansion of macro '__argp_fmtstream_set_wmargin'
  456 | __argp_fmtstream_set_wmargin (argp_fmtstream_t __fs, size_t __wmargin)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:204:38: note: previous definition of 'argp_fmtstream_set_wmargin' with type 'size_t(struct argp_fmtstream *, size_t)' {aka 'long unsigned int(struct argp_fmtstream *, long unsigned int)'}
  204 | #define __argp_fmtstream_set_wmargin argp_fmtstream_set_wmargin
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:276:1: note: in expansion of macro '__argp_fmtstream_set_wmargin'
  276 | __argp_fmtstream_set_wmargin (argp_fmtstream_t __fs, size_t __wmargin)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:72:32: error: redefinition of 'argp_fmtstream_point'
   72 | #define __argp_fmtstream_point argp_fmtstream_point
      |                                ^~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:468:1: note: in expansion of macro '__argp_fmtstream_point'
  468 | __argp_fmtstream_point (argp_fmtstream_t __fs)
      | ^~~~~~~~~~~~~~~~~~~~~~
In file included from freeipmi-argp-fmtstream.c:34:
freeipmi-argp-fmtstream.h:205:32: note: previous definition of 'argp_fmtstream_point' with type 'size_t(struct argp_fmtstream *)' {aka 'long unsigned int(struct argp_fmtstream *)'}
  205 | #define __argp_fmtstream_point argp_fmtstream_point
      |                                ^~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.h:288:1: note: in expansion of macro '__argp_fmtstream_point'
  288 | __argp_fmtstream_point (argp_fmtstream_t __fs)
      | ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:510: libportability_la-freeipmi-argp-fmtstream.lo] Error 1
make[2]: Leaving directory '/cygdrive/c/Users/crd/src/freeipmi-1.6.10/common/portability'
make[1]: *** [Makefile:427: all-recursive] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/crd/src/freeipmi-1.6.10/common'
make: *** [Makefile:609: all-recursive] Error 1
```

**NOTE:** these duplicate definitions might actually indicate a broader problem than just with Cygwin, possibly with the gcc version or something. 

This is the environment I'm working with:
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/11/lto-wrapper.exe
Target: x86_64-pc-cygwin
Configured with: /mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.3.0/configure --srcdir=/mnt/share/cygpkgs/gcc/gcc.x86_64/src/gcc-11.3.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --with-gcc-major-version-only --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=c,c++,fortran,lto,objc,obj-c++,jit --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --enable-libquadmath --enable-libquadmath-support --disable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (GCC)
```

**Comment by chu11** [comment]
thanks @crd477.  I'll admit I don't understand what's going on in that file, there's a ton of portability stuff and I can't quite grok what is their ultimate goal.  I stole those files from `glibc` a long time ago.

Which makes me think, perhaps if I stole it from a newer glibc there could be fixes for your case.  Let me dig up a newer file later today.

**Comment by chu11** [comment]
Looking at some more recent glibc argparse implementations, there doesn't seem to be anything in there that could fix your issue.

It seems that all your changes occur within the `__OPTIMIZE__` block.  I'm wondering if the following might work instead?

```
diff --git a/common/portability/freeipmi-argp-fmtstream.h b/common/portability/freeipmi-argp-fmtstream.h
index 0e00237..fea5454 100644
--- a/common/portability/freeipmi-argp-fmtstream.h
+++ b/common/portability/freeipmi-argp-fmtstream.h
@@ -192,7 +192,7 @@ extern void __argp_fmtstream_update (argp_fmtstream_t __fs);
 extern int _argp_fmtstream_ensure (argp_fmtstream_t __fs, size_t __amount);
 extern int __argp_fmtstream_ensure (argp_fmtstream_t __fs, size_t __amount);
 ^L
-#ifdef __OPTIMIZE__
+#if defined(__OPTIMIZE__) && !defined(__CYGWIN__)
 /* Inline versions of above routines.  */
 
 #if !_LIBC
@@ -304,7 +304,7 @@ __argp_fmtstream_point (argp_fmtstream_t __fs)
 #undef __argp_fmtstream_ensure
 #endif
 
-#endif /* __OPTIMIZE__ */
+#endif /* __OPTIMIZE__ && !__CYGWIN__*/
 
 #endif /* ARGP_FMTSTREAM_USE_LINEWRAP */
```

i.e. do not optimize if you are on cygwin.

**Comment by crd477** [comment]
Yep, I agree.  That looks better.
This version seems to work on my system as well.  I've only done casual usage testing so far.

**Comment by chu11** [comment]
great, I've pushed it into the stable branch:

https://github.com/chu11/freeipmi-mirror/tree/freeipmi-1-6-0-stable

it'll be out with the next FreeIPMI release.  Thanks for reporting this.  I"ll consider the issue closed, feel free to re-open if there's a problem in the branch.

**Pull request closed without merging**
